In [1]:
import numpy as np
print("Numpy Version = ", np.__version__)

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

Numpy Version =  1.26.2
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
arr = np.array(42)
print(arr)

42


In [3]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print("The Dimenion of array is: ",arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
The Dimenion of array is:  3


In [5]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]], ndmin = 2)
print(arr)
print("The Dimenion of array is: ",arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
The Dimenion of array is:  3


### Numpy Array Indexing

In [6]:
arr = np.array([1,2,3,4,5,7])


print(arr[5])
print(arr[0] + arr[3])


7
5


In [7]:
arr = np.array([[1,2,3,4,5,6],[7,6,5,4,3,2]])
print(arr[1,0])

7


### Numpy Array Slicing

In [8]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
x = arr[1:4]
print(x)

[15 20 25]


In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
x = arr[5:]
print(x)

[6 7 8 9 0]


In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
x = arr[:5]
print(x)

[1 2 3 4 5]


In [11]:
arr = ([1,2,3,4,5,6,7])
x = arr[-1:]
y = arr[:-1]
print(x)
print(y)

[7]
[1, 2, 3, 4, 5, 6]


In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
x = arr[1:8:3]
print(x)

[2 5 8]


In [13]:
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
x = arr[1, 1:4]
print(x)

[ 8  9 10]


In [14]:
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
x = arr[0:2, 1:4]
print(x)

[[ 2  3  4]
 [ 8  9 10]]


### Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent ther type ( void )


In [15]:
arr = np.array(["apple","banana","Mango"])
print(arr.dtype)

<U6


In [16]:
arr = np.array([1,3,4,5,6])

newarr = arr.astype("f")

print(arr)
print(newarr)

[1 3 4 5 6]
[1. 3. 4. 5. 6.]


In [17]:
arr = np.array([1.43,3.56,4.67,5.23,6.45])

newarr = arr.astype("i")

print(arr)
print(newarr)
print(newarr.dtype)

[1.43 3.56 4.67 5.23 6.45]
[1 3 4 5 6]
int32


In [18]:
arr = np.array([1.43,3.56,4.67,5.23,6.45])

newarr = arr.astype(bool)

print(arr)
print(newarr)
print(newarr.dtype)

[1.43 3.56 4.67 5.23 6.45]
[ True  True  True  True  True]
bool


### Numpy Copy vs View

In [19]:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
x[1] = 54

print(arr)
print(x)

[1 2 3 4 5]
[ 1 54  3  4  5]


In [20]:
arr = np.array([1,2,3,4,5])
x = arr.view()
x[1] = 54

print(arr)
print(x)

[ 1 54  3  4  5]
[ 1 54  3  4  5]


In [21]:
arr = np.array([1,2,3,4,5,6,7,8])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5 6 7 8]


In [27]:
arr = np.array([[67,98,65,87],[1,2,3,4]])
print(arr.shape)

(2, 4)


In [31]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
newarr = arr.reshape(2,5)
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [35]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [36]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,12,45])
newarr = arr.reshape(2,-1) #-1 for unknown dimenstion,NumPy will calcylate it.
print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 12 45]]
